"""Coverage tracer plugin — instruments a repo and collects JSONL call traces.

This is a TracerPlugin.  It:
  - install():  writes a conftest.py or sitecustomize.py inside
                ``.repograph/`` so the next test run generates trace files in
                ``.repograph/runtime/``.  Nothing is written to the repo root.
  - collect():  returns the list of .jsonl files written.

The conftest.py is placed at ``.repograph/conftest.py``.  Pytest discovers
conftest files by walking the directory tree from the rootdir, so it picks
up ``.repograph/conftest.py`` automatically when pytest is run from the repo
root without any configuration changes.

The trace files are in the ``jsonl_call_trace`` format defined in
repograph.runtime.trace_format.  After collection, the
RuntimeOverlayDynamicPlugin consumes them on the next sync.

CLI usage
---------
    repograph trace install    → calls install()
    repograph trace collect    → calls collect(), prints summary
    repograph sync             → on_traces_collected fires overlay

Note: Routine users should prefer ``repograph sync --full``, which runs
traced tests automatically without any manual install step.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from repograph.core.plugin_framework import PluginManifest, TracerPlugin
from repograph.runtime.trace_format import TRACE_FORMAT, live_trace_dir


_CONFTEST_TEMPLATE = '''\
"""RepoGraph dynamic trace conftest — auto-generated by repograph trace install.
Delete this file to stop tracing.
"""
from repograph.runtime.tracer import SysTracer as _ST
from repograph.runtime.trace_policy import TracePolicy
import pytest as _pytest

_tracer = None

def pytest_sessionstart(session):
    global _tracer
    _tracer = _ST(
        repo_root={repo_root!r},
        repograph_dir={repograph_dir!r},
        session_name="pytest",
        trace_policy={trace_policy_expr},
    )
    _tracer.start()

def pytest_sessionfinish(session, exitstatus):
    global _tracer
    if _tracer:
        _tracer.stop()
        print(f"\\n[repograph] trace: {{_tracer.trace_path}}")
        _tracer = None
'''

_SITECUSTOMIZE_TEMPLATE = '''\
"""RepoGraph dynamic trace sitecustomize — auto-generated.
Delete to stop tracing.
"""
import atexit as _atexit
from repograph.runtime.tracer import SysTracer as _ST
from repograph.runtime.trace_policy import TracePolicy

_tracer = _ST(
    repo_root={repo_root!r},
    repograph_dir={repograph_dir!r},
    session_name="sitecustomize",
    trace_policy={trace_policy_expr},
    trace_subdir="live",
    publish_live_session=True,
)
_tracer.start()
_atexit.register(_tracer.stop)
'''


class CoverageTracerPlugin(TracerPlugin):
    """Instruments a repository via pytest conftest or sitecustomize."""

    manifest = PluginManifest(
        id="tracer.coverage",
        name="Coverage tracer",
        kind="tracer",
        description=(
            "Writes a pytest conftest.py (or sitecustomize.py) that collects "
            "JSONL call traces via sys.settrace during test execution."
        ),
        hooks=("on_tracer_install", "on_tracer_collect"),
        trace_format=TRACE_FORMAT,
    )

    def install(
        self,
        repo_root: Path,
        trace_dir: Path,
        *,
        mode: str = "pytest",
        **kwargs: Any,
    ) -> dict:
        """Write instrumentation config inside ``.repograph/``.

        Parameters
        ----------
        repo_root:
            Absolute path to repository root.
        trace_dir:
            Destination for trace files (``.repograph/runtime/``).
        mode:
            ``"pytest"`` — write ``.repograph/conftest.py`` (default).
            Pytest discovers it automatically when run from the repo root.
            ``"sitecustomize"`` — write ``.repograph/sitecustomize.py``
            (traces all Python processes launched from this tree).

        Returns
        -------
        dict with keys: mode, config_path, trace_dir, status.
        """
        repo_root = Path(repo_root).resolve()
        repograph_dir_path = trace_dir.parent  # .repograph/
        repograph_dir = str(repograph_dir_path)
        repograph_dir_path.mkdir(parents=True, exist_ok=True)

        policy_expr = (
            "TracePolicy.from_kwargs("
            f"max_records={int(kwargs.get('max_records') or 0)!r}, "
            f"max_file_bytes={int(kwargs.get('max_file_bytes') or 0)!r}, "
            f"rotate_files={int(kwargs.get('rotate_files') or 0)!r}, "
            f"sample_rate={float(kwargs.get('sample_rate') or 1.0)!r}, "
            f"include_pattern={str(kwargs.get('include_pattern') or '')!r}, "
            f"exclude_pattern={str(kwargs.get('exclude_pattern') or '')!r}"
            ")"
        )

        if mode == "sitecustomize":
            # sitecustomize.py lives inside .repograph/ so it never pollutes
            # the repo root — users add .repograph to PYTHONPATH if needed.
            config_path = repograph_dir_path / "sitecustomize.py"
            effective_trace_dir = live_trace_dir(repograph_dir_path)
            content = _SITECUSTOMIZE_TEMPLATE.format(
                repo_root=str(repo_root),
                repograph_dir=repograph_dir,
                trace_policy_expr=policy_expr,
            )
        else:
            # conftest.py lives inside .repograph/ — pytest discovers it via
            # its standard upward conftest scan when run from the repo root.
            config_path = repograph_dir_path / "conftest.py"
            if config_path.exists():
                existing = config_path.read_text(encoding="utf-8")
                if "repograph" in existing:
                    return {
                        "mode": mode,
                        "config_path": str(config_path),
                        "trace_dir": str(trace_dir),
                        "status": "already_installed",
                    }
            effective_trace_dir = trace_dir
            content = _CONFTEST_TEMPLATE.format(
                repo_root=str(repo_root),
                repograph_dir=repograph_dir,
                trace_policy_expr=policy_expr,
            )

        effective_trace_dir.mkdir(parents=True, exist_ok=True)
        config_path.write_text(content, encoding="utf-8")

        return {
            "mode": mode,
            "config_path": str(config_path),
            "trace_dir": str(effective_trace_dir),
            "status": "installed",
        }

    def collect(self, trace_dir: Path, **kwargs: Any) -> list[Path]:
        """Return list of trace files written to trace_dir."""
        if not trace_dir.exists():
            return []
        files = sorted(trace_dir.glob("*.jsonl"))
        return files


def build_plugin() -> CoverageTracerPlugin:
    return CoverageTracerPlugin()
