"""Remove local development artifacts (caches, trace bootstrap files, etc.)."""
from __future__ import annotations

import os
import shutil
from pathlib import Path

# Markers for auto-generated trace install files (see coverage_tracer plugin).
_MARKER_CONFTEST = "RepoGraph dynamic trace conftest — auto-generated by repograph trace install"
_MARKER_SITECUSTOM = "RepoGraph dynamic trace sitecustomize — auto-generated"

_EXAMPLE_CONFTEST = "conftest_repograph_trace_install.example.py"

# Virtual environment directory names at repository root only.
_ROOT_VENV_NAMES = frozenset({".venv", "venv", "env"})

# Directory names to remove anywhere under the repo (except under .git / node_modules).
_CACHE_DIR_NAMES = frozenset({
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".hypothesis",
    ".tox",
})

# Optional build output dirs at repo root only.
_ROOT_ARTIFACT_DIRS = frozenset({"build", "dist"})

# Do not descend into these (keeps scans fast and avoids touching dependencies).
_SKIP_DESCENT_NAMES = frozenset({".git", "node_modules"})


def _walk_pruned(root: Path):
    """Recursively walk *root*; never enters ``.git/`` or ``node_modules/``."""
    root = root.resolve()
    for dirpath, dirnames, filenames in os.walk(root, topdown=True):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DESCENT_NAMES]
        yield Path(dirpath), dirnames, filenames


def _remove_cache_dirs_recursive(root: Path) -> list[str]:
    """Find and remove cache-like dirs at any depth (full tree under *root*)."""
    found: list[Path] = []
    for dirpath, dirnames, _ in os.walk(root, topdown=True):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DESCENT_NAMES]
        dp = Path(dirpath)
        n = dp.name
        if n in _CACHE_DIR_NAMES or n.endswith(".egg-info"):
            found.append(dp)
            dirnames[:] = []
    removed: list[str] = []
    for p in sorted(found, key=lambda x: -len(x.parts)):
        if p.is_dir():
            try:
                shutil.rmtree(p)
                removed.append(str(p))
            except OSError:
                pass
    return removed


def _remove_pyc_and_ds_recursive(root: Path) -> list[str]:
    """Remove stray ``.pyc`` and ``.DS_Store`` files after cache dirs are gone."""
    removed: list[str] = []
    for dp, _, filenames in _walk_pruned(root):
        for fn in filenames:
            if fn.endswith(".pyc") or fn == ".DS_Store":
                fp = dp / fn
                if fp.is_file():
                    try:
                        fp.unlink()
                        removed.append(str(fp))
                    except OSError:
                        pass
    return removed


def _remove_cache_dirs_shallow(root: Path) -> list[str]:
    """Only immediate children of *root* that match cache dir names."""
    removed: list[str] = []
    try:
        for child in sorted(root.iterdir()):
            if not child.is_dir():
                continue
            n = child.name
            if n in _CACHE_DIR_NAMES or n.endswith(".egg-info"):
                try:
                    shutil.rmtree(child)
                    removed.append(str(child))
                except OSError:
                    pass
    except OSError:
        pass
    return removed


def _remove_pyc_and_ds_shallow(root: Path) -> list[str]:
    """Only the repo root directory (no subfolders)."""
    removed: list[str] = []
    try:
        for child in root.iterdir():
            if not child.is_file():
                continue
            if child.name.endswith(".pyc") or child.name == ".DS_Store":
                try:
                    child.unlink()
                    removed.append(str(child))
                except OSError:
                    pass
    except OSError:
        pass
    return removed


def clean_development_artifacts(repo_root: Path, *, recursive: bool = True) -> list[str]:
    """Delete caches, junk files, trace helper files, and root-level venv dirs.

    When *recursive* is True (default), walks the entire repository tree (except
    ``.git/`` and ``node_modules/``) so ``__pycache__`` and other cache dirs are
    found at any depth. When False, only removes matching directories that are
    direct children of the repo root, plus a shallow ``*.pyc`` / ``.DS_Store``
    pass via :func:`pathlib.Path.rglob`.

    Returns a chronologically merged list of removed paths (as strings) for logging.
    """
    root = repo_root.resolve()
    removed: list[str] = []

    # --- Accidental mock-derived artifact roots ---
    # Some unit test regressions can leak MagicMock-derived paths into runner code,
    # which can create a repo-root "MagicMock/" directory. This is never a valid
    # user artifact; remove it as part of dev clean.
    magicmock_dir = root / "MagicMock"
    if magicmock_dir.is_dir():
        try:
            shutil.rmtree(magicmock_dir)
            removed.append(str(magicmock_dir))
        except OSError:
            pass

    # --- Root-level venv / build dirs ---
    for name in sorted(_ROOT_VENV_NAMES | _ROOT_ARTIFACT_DIRS):
        p = root / name
        if p.is_dir():
            shutil.rmtree(p)
            removed.append(str(p))

    # --- Cache / egg-info dirs ---
    if recursive:
        removed.extend(_remove_cache_dirs_recursive(root))
    else:
        removed.extend(_remove_cache_dirs_shallow(root))

    # --- macOS / zip junk at repo root ---
    macosx = root / "__MACOSX"
    if macosx.is_dir():
        shutil.rmtree(macosx)
        removed.append(str(macosx))

    # --- Stray .pyc and .DS_Store (recursive walk skips .git / node_modules) ---
    if recursive:
        removed.extend(_remove_pyc_and_ds_recursive(root))
    else:
        removed.extend(_remove_pyc_and_ds_shallow(root))

    # --- Example copy-to-conftest template (setup helper) ---
    ex = root / _EXAMPLE_CONFTEST
    if ex.is_file():
        try:
            ex.unlink()
            removed.append(str(ex))
        except OSError:
            pass

    # --- Auto-generated trace install configs (written to .repograph/ by the plugin) ---
    for fname, marker in (
        ("conftest.py", _MARKER_CONFTEST),
        ("sitecustomize.py", _MARKER_SITECUSTOM),
    ):
        cfg = root / ".repograph" / fname
        if not cfg.is_file():
            continue
        try:
            head = cfg.read_text(encoding="utf-8", errors="replace")[:400]
        except OSError:
            continue
        if marker in head:
            try:
                cfg.unlink()
                removed.append(str(cfg))
            except OSError:
                pass

    return removed


def summarize_removed(paths: list[str]) -> str:
    if not paths:
        return "No matching dev artifacts found."
    lines = [f"  · {p}" for p in paths[:200]]
    if len(paths) > 200:
        lines.append(f"  … and {len(paths) - 200} more")
    return "\n".join(lines)
