"""Function-level test coverage overlay plugin (Block I4).

Reads a ``coverage.json`` file generated by ``pytest-cov`` (or the ``coverage``
package directly via ``coverage json``) and marks each Function node in the
graph with ``is_covered: bool`` based on whether its source lines are
fully covered.

A function is considered **covered** when every line in its body that appears in
the coverage data is recorded as executed.  The comparison is line-range based
(``line_start`` to ``line_end`` inclusive) rather than symbol-name based, so it
works across all languages that produce line-coverage data.

The plugin also emits a per-layer coverage summary to stdout/logs.

Coverage report format
----------------------
``coverage json`` writes a file with this structure::

    {
        "meta": {...},
        "files": {
            "path/to/file.py": {
                "executed_lines": [1, 3, 5, ...],
                "missing_lines":  [2, 4, ...],
                ...
            }
        }
    }

Usage
-----
1. Run your tests with ``pytest --cov --cov-report=json``
2. Run ``repograph sync`` — the plugin fires on ``on_traces_collected``
   and reads ``.coverage_json_path`` from the hook kwargs, or falls back
   to ``coverage.json`` in the repo root.

Alternatively, call directly::

    from repograph.plugins.dynamic_analyzers.coverage_overlay.plugin import (
        apply_coverage_json,
    )
    stats = apply_coverage_json(store, coverage_json_path="coverage.json")
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

from repograph.core.plugin_framework import DynamicAnalyzerPlugin, PluginManifest

_logger = logging.getLogger(__name__)


class CoverageOverlayPlugin(DynamicAnalyzerPlugin):
    manifest = PluginManifest(
        id="dynamic.coverage_overlay",
        name="Pytest-cov coverage overlay",
        kind="dynamic_analyzer",
        description=(
            "Reads coverage.json from pytest-cov and marks each Function "
            "node with is_covered:bool based on line-range intersection."
        ),
        requires=(),
        produces=("artifacts.coverage_summary",),
        hooks=("on_traces_collected",),
        order=60,
    )

    def analyze_traces(
        self,
        trace_dir,  # type: ignore[override]  # unused — coverage reads coverage.json not trace dir
        store: Any,
        **kwargs: Any,
    ) -> list[dict]:
        """Satisfy the DynamicAnalyzerPlugin ABC; delegates to analyze()."""
        result = self.analyze(store=store, **kwargs)
        return [result] if result else []

    def analyze(self, **kwargs: Any) -> dict[str, Any]:
        store = kwargs.get("store")
        repo_root: str = kwargs.get("repo_root", "")
        coverage_json_path: str | None = kwargs.get("coverage_json_path")

        if store is None:
            return {}

        # Locate coverage.json — explicit kwarg wins, then repo root fallback
        if not coverage_json_path:
            if repo_root:
                candidate = os.path.join(repo_root, "coverage.json")
                if os.path.exists(candidate):
                    coverage_json_path = candidate
        if not coverage_json_path or not os.path.exists(coverage_json_path):
            _logger.debug(
                "coverage_overlay: coverage.json not found — skipping "
                "(run pytest --cov --cov-report=json to generate it)"
            )
            return {}

        stats = apply_coverage_json(store, coverage_json_path=coverage_json_path)
        _emit_layer_summary(store, stats)
        return {"coverage_stats": stats}


def build_plugin() -> CoverageOverlayPlugin:
    return CoverageOverlayPlugin()


# ---------------------------------------------------------------------------
# Core implementation (callable standalone for testing and CLI use)
# ---------------------------------------------------------------------------


def apply_coverage_json(
    store,
    *,
    coverage_json_path: str,
) -> dict[str, Any]:
    """Read ``coverage.json`` and mark Function nodes with ``is_covered``.

    Parameters
    ----------
    store:
        Open ``GraphStore`` instance.
    coverage_json_path:
        Absolute path to the JSON coverage report.

    Returns
    -------
    Summary dict::

        {
            "total": int,
            "covered": int,
            "uncovered": int,
            "coverage_pct": float,   # 0–100
            "files_processed": int,
        }
    """
    with open(coverage_json_path, encoding="utf-8") as f:
        cov_data = json.load(f)

    files: dict[str, dict] = cov_data.get("files", {})
    if not files:
        _logger.debug("coverage_overlay: coverage.json has no 'files' key")
        return {"total": 0, "covered": 0, "uncovered": 0, "coverage_pct": 0.0, "files_processed": 0}

    # Build: {file_path -> set of executed line numbers}
    executed_map: dict[str, set[int]] = {}
    for raw_path, file_info in files.items():
        executed = set(file_info.get("executed_lines") or [])
        # Normalise: coverage.json may use absolute paths or repo-relative paths
        norm = raw_path.replace("\\", "/")
        executed_map[norm] = executed
        # Also index by basename for fuzzy matching
        executed_map[os.path.basename(norm)] = executed

    # Fetch all functions with their line ranges and file paths
    try:
        rows = store.query(
            "MATCH (f:Function) RETURN f.id, f.file_path, f.line_start, f.line_end"
        )
    except Exception as exc:
        _logger.warning("coverage_overlay: function query failed: %s", exc)
        return {}

    total = len(rows)
    covered_count = 0
    files_seen: set[str] = set()

    for r in rows:
        fn_id, file_path, line_start, line_end = r[0], r[1], r[2], r[3]
        if not fn_id or not file_path:
            continue

        norm_path = (file_path or "").replace("\\", "/")
        executed = (
            executed_map.get(norm_path)
            or executed_map.get(os.path.basename(norm_path))
        )
        if executed is None:
            # File not in coverage data → treat as not covered
            store.update_function_coverage(fn_id, is_covered=False)
            continue

        files_seen.add(norm_path)
        ls = int(line_start or 0)
        le = int(line_end or ls)

        # A function is covered if at least one of its body lines was executed.
        # We exclude the def/class header line (ls) from the required set because
        # coverage tools sometimes don't mark decorators or function signatures.
        body_lines = set(range(ls + 1, le + 1)) if le > ls else {ls}
        is_covered = bool(body_lines & executed)

        store.update_function_coverage(fn_id, is_covered=is_covered)
        if is_covered:
            covered_count += 1

    coverage_pct = (covered_count / total * 100) if total > 0 else 0.0
    _logger.info(
        "coverage_overlay: %d/%d functions covered (%.1f%%)",
        covered_count, total, coverage_pct,
    )
    return {
        "total": total,
        "covered": covered_count,
        "uncovered": total - covered_count,
        "coverage_pct": round(coverage_pct, 2),
        "files_processed": len(files_seen),
    }


def _emit_layer_summary(store, stats: dict[str, Any]) -> None:
    """Log coverage broken down by layer (requires Block G layer classification)."""
    try:
        rows = store.query(
            "MATCH (f:Function) RETURN f.layer, f.is_covered"
        )
    except Exception:
        return

    from collections import defaultdict, Counter
    layer_counts: dict[str, Counter] = defaultdict(Counter)
    for r in rows:
        layer = r[0] or "unknown"
        is_cov = bool(r[1])
        layer_counts[layer]["total"] += 1
        if is_cov:
            layer_counts[layer]["covered"] += 1

    for layer, counts in sorted(layer_counts.items()):
        t = counts["total"]
        c = counts["covered"]
        pct = (c / t * 100) if t > 0 else 0.0
        _logger.info(
            "coverage_overlay layer=%s: %d/%d covered (%.1f%%)", layer, c, t, pct
        )
