from __future__ import annotations

"""Config_Registry exporter plugin — all logic lives here. Fires on: on_export."""

"""Phase 17 — Config Registry: global config-key → consumer mapping.

Aggregates all config key reads discovered during pathway context generation
(Phase 14) and source-level scanning across all indexed files.  Writes a
``config_registry.json`` index to ``.repograph/meta/`` so the
``repograph config`` command can surface it instantly.

Output schema (``config_registry.json``)
------------------------------------------
.. code-block:: json

    {
      "trading": {
        "pathways": ["champion_bot_tick_flow", "async_main_flow"],
        "files":    ["src/bots/champion_bot.py", "src/app/bootstrap.py"],
        "usage_count": 7
      },
      ...
    }
"""

import ast
import re
from collections import defaultdict

from repograph.graph_store.store import GraphStore
from repograph.core.plugin_framework import ExporterPlugin, PluginManifest as _Manifest
from repograph.plugins.utils import write_meta_json
from repograph.utils.path_classifier import is_test_path

# Patterns for extracting config key reads from source code — mirrors
# those in context/formatter.py so the registry stays in sync.
_CONFIG_PATTERNS = [
    re.compile(r"""(?:cfg|config|settings|conf)\s*\[\s*["']([^"']+)["']\s*\]"""),
    re.compile(r"""(?:cfg|config|settings|conf)\.get\s*\(\s*["']([^"']+)["']"""),
    re.compile(r"""os\.(?:getenv|environ\.get|environ\[)\s*\(?["']([^"']+)["']"""),
]

# Keys to exclude: they are ubiquitous framework internals, not meaningful
# application config keys.
_EXCLUDE_KEYS = frozenset({
    "PATH", "HOME", "USER", "SHELL", "TERM", "LANG", "LC_ALL",
    "PYTHONPATH", "VIRTUAL_ENV", "PWD",
})

# Single-letter keys from fixtures/tests (cfg["a"], etc.) — not meaningful app config.
_TRIVIAL_KEYS = frozenset(chr(i) for i in range(ord("a"), ord("z") + 1)) | frozenset(
    chr(i) for i in range(ord("A"), ord("Z") + 1)
) | frozenset(str(i) for i in range(10))


def _key_excluded(key: str) -> bool:
    return key in _EXCLUDE_KEYS or key in _TRIVIAL_KEYS


def run(store: GraphStore, repograph_dir: str, include_tests: bool = False) -> dict[str, dict]:
    """Build the config-key registry and write config_registry.json.

    Args:
        store: open GraphStore for the indexed repository.
        repograph_dir: path to the ``.repograph/`` directory.
        include_tests: when True, include keys from test files and test paths.

    Returns:
        Registry dict: ``{key_name: {pathways, files, usage_count}}``.
    """
    registry, diagnostics = build_registry_with_diagnostics(store, include_tests=include_tests)
    _write_json(registry, repograph_dir)
    _write_diagnostics_json(diagnostics, repograph_dir)
    return registry


def build_registry(store: GraphStore, include_tests: bool = False) -> dict[str, dict]:
    """Build registry dict without writing JSON (e.g. ``repograph config --include-tests``)."""
    registry, _diag = _build_registry(store, include_tests=include_tests)
    return registry


def build_registry_with_diagnostics(
    store: GraphStore,
    include_tests: bool = False,
) -> tuple[dict[str, dict], dict]:
    """Build registry and diagnostics without writing JSON."""
    return _build_registry(store, include_tests=include_tests)


# ---------------------------------------------------------------------------
# Registry construction
# ---------------------------------------------------------------------------

def _build_registry(store: GraphStore, include_tests: bool = False) -> tuple[dict[str, dict], dict]:
    """Scan pathways + all source files and aggregate config key usage."""

    diagnostics = {
        "status": "ok",
        "include_tests": bool(include_tests),
        "pathways_total": 0,
        "pathways_with_context": 0,
        "source_files_seen": 0,
        "source_files_scanned": 0,
        "source_files_skipped_non_source": 0,
        "source_files_skipped_test": 0,
        "source_files_read_errors": 0,
        "keys_extracted_total": 0,
        "errors": [],
    }
    # key → {pathways: set, files: set, usage_count: int}
    registry: dict[str, dict] = defaultdict(lambda: {
        "pathways": set(),
        "files": set(),
        "usage_count": 0,
    })

    # ── 1. Mine pathway context docs (already generated by Phase 14) ────────
    try:
        pathways = store.query(
            """
            MATCH (p:Pathway)
            RETURN p.id, p.name, p.context_doc
            """
        )
        diagnostics["pathways_total"] = len(pathways)
        for pathway_id, pw_name, ctx_doc in pathways:
            pw_name = pw_name or ""
            ctx_doc = ctx_doc or ""
            if not ctx_doc:
                continue
            diagnostics["pathways_with_context"] += 1
            keys = _extract_from_context_doc(ctx_doc)
            for key in keys:
                if _key_excluded(key):
                    continue
                registry[key]["pathways"].add(pw_name)
                registry[key]["usage_count"] += 1
                diagnostics["keys_extracted_total"] += 1
                for fp in _pathway_participating_files(store, pathway_id):
                    if not include_tests and fp and is_test_path(fp):
                        continue
                    registry[key]["files"].add(fp)
    except Exception as exc:
        diagnostics["errors"].append(f"pathways_scan:{type(exc).__name__}: {exc}")

    # ── 2. Scan all source files directly ───────────────────────────────────
    try:
        all_files = store.get_all_files()
        for f in all_files:
            diagnostics["source_files_seen"] += 1
            fp = f.get("path", "") or f.get("abs_path", "")
            if not fp:
                continue
            if not include_tests and is_test_path(fp):
                diagnostics["source_files_skipped_test"] += 1
                continue
            # Only scan Python and JS/TS — shell/HTML config access is noisier
            lang = f.get("language", "")
            if lang not in ("python", "javascript", "typescript"):
                diagnostics["source_files_skipped_non_source"] += 1
                continue
            try:
                abs_p = f.get("abs_path") or fp
                with open(abs_p, encoding="utf-8", errors="replace") as fh:
                    source = fh.read()
            except OSError:
                diagnostics["source_files_read_errors"] += 1
                continue
            diagnostics["source_files_scanned"] += 1
            keys = _extract_from_source(source, lang)
            for key in keys:
                if _key_excluded(key):
                    continue
                registry[key]["files"].add(fp)
                registry[key]["usage_count"] += 1
                diagnostics["keys_extracted_total"] += 1
    except Exception as exc:
        diagnostics["errors"].append(f"source_scan:{type(exc).__name__}: {exc}")

    # ── 3. Serialise sets to sorted lists ───────────────────────────────────
    result: dict[str, dict] = {}
    for key, data in sorted(registry.items(), key=lambda x: -x[1]["usage_count"]):
        result[key] = {
            "pathways": sorted(data["pathways"]),
            "files": sorted(data["files"]),
            "usage_count": data["usage_count"],
        }
    diagnostics["registry_keys"] = len(result)
    if diagnostics["errors"]:
        diagnostics["status"] = "empty_error" if not result else "ok_with_errors"
    elif not result:
        diagnostics["status"] = "empty_valid"
    return result, diagnostics


def _pathway_participating_files(store: GraphStore, pathway_id: str) -> list[str]:
    """Return distinct file paths that participate in one pathway."""
    try:
        steps = store.get_pathway_steps(pathway_id)
    except Exception:
        return []
    return list(
        dict.fromkeys(
            step.get("file_path", "")
            for step in steps
            if step.get("file_path")
        )
    )


def _extract_from_source(source: str, language: str = "") -> list[str]:
    """Return all config key names found in source code."""
    keys: set[str] = set()
    for pattern in _CONFIG_PATTERNS:
        for m in pattern.finditer(source):
            k = m.group(1).strip()
            if k and len(k) <= 80:
                keys.add(k)
    if language == "python":
        keys.update(_extract_python_dotted_keys(source))
    return list(keys)


_CFG_NAMES = frozenset({"cfg", "config", "settings", "conf"})


def _slice_key(sl: ast.AST) -> str | None:
    if isinstance(sl, ast.Constant) and isinstance(sl.value, str):
        return sl.value
    return None


def _chain_from_subscript(node: ast.Subscript) -> list[str] | None:
    parts: list[str] = []
    cur: ast.AST = node
    while isinstance(cur, ast.Subscript):
        k = _slice_key(cur.slice)
        if not k:
            return None
        parts.append(k)
        cur = cur.value
    if isinstance(cur, ast.Name) and cur.id in _CFG_NAMES:
        return list(reversed(parts))
    return None


def _extract_python_dotted_keys(source: str) -> set[str]:
    """``cfg['a']['b']`` → ``a``, ``a.b``."""
    out: set[str] = set()
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return out

    class V(ast.NodeVisitor):
        def visit_Subscript(self, node: ast.Subscript) -> None:
            ch = _chain_from_subscript(node)
            if ch:
                for i in range(len(ch)):
                    out.add(".".join(ch[: i + 1]))
            self.generic_visit(node)

        def visit_Call(self, node: ast.Call) -> None:
            if isinstance(node.func, ast.Attribute) and node.func.attr == "get":
                if isinstance(node.func.value, ast.Name) and node.func.value.id in _CFG_NAMES:
                    if node.args and isinstance(node.args[0], ast.Constant):
                        out.add(str(node.args[0].value))
            self.generic_visit(node)

    V().visit(tree)
    return out


def _extract_from_context_doc(doc: str) -> list[str]:
    """Extract config keys from the CONFIG DEPENDENCIES section of a pathway doc."""
    keys: set[str] = set()
    in_config_section = False
    for line in doc.split("\n"):
        stripped = line.strip()
        if stripped == "CONFIG DEPENDENCIES":
            in_config_section = True
            continue
        if in_config_section:
            if stripped.startswith("•"):
                key = stripped.lstrip("• ").strip()
                if key and len(key) <= 80:
                    keys.add(key)
                continue
            # Section ends at next all-caps header or box-drawing char
            if stripped and (stripped[0] in "═┌└│" or (stripped.isupper() and len(stripped) > 3)):
                in_config_section = False
                continue
    return list(keys)


def _write_json(payload, repograph_dir: str) -> None:
    """Persist JSON artefact to .repograph/meta/."""
    write_meta_json(repograph_dir, "config_registry.json", payload)


def _write_diagnostics_json(payload, repograph_dir: str) -> None:
    """Persist config registry diagnostics."""
    write_meta_json(repograph_dir, "config_registry_diagnostics.json", payload)


class ConfigRegistryExporterPlugin(ExporterPlugin):
    manifest = _Manifest(
        id="exporter.config_registry",
        name="Config_Registry exporter",
        kind="exporter",
        description="Writes config_registry artefact to .repograph/meta/.",
        requires=("config_registry",),
        produces=("artifacts.config_registry_json",),
        hooks=("on_export",),
        order=240,
        after=("exporter.pathway_contexts",),
    )

    def export(self, store=None, repograph_dir: str = "", config=None, **kwargs):
        if store is None:
            return {}
        include_tests = bool(getattr(config, "include_tests_config_registry", False))
        result, diagnostics = build_registry_with_diagnostics(store, include_tests=include_tests)
        _write_json(result, repograph_dir)
        _write_diagnostics_json(diagnostics, repograph_dir)
        return {
            "kind": "config_registry",
            "written": True,
            "result": result,
            "diagnostics": diagnostics,
        }


def build_plugin() -> ConfigRegistryExporterPlugin:
    return ConfigRegistryExporterPlugin()
